services:
  postgres:
    image: postgres:15.2
    container_name: postgres_db_clientes
    restart: always
    environment:
      POSTGRES_DB: db_clientes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - db:/data/db

volumes:
  postgres_data:
  db: