server:
  port: ${PORT:8080}
  servlet:
    context-path: /db_clientes

spring:
  application:
    name: db_clientes
  datasource:
    url: jdbc:postgresql://localhost:5432/db_clientes
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
          lob.non_contextual_creation: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
      open-in-view: false